name: Refresh Token Keepalive

on:
  schedule:
    # Every 4 months (Jan, May, Sep) on the 1st at 00:00 UTC
    - cron: '0 0 1 1,5,9 *'
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Google OAuth to keep refresh token alive
        env:
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        run: |
          curl -s -X POST https://oauth2.googleapis.com/token \
            -d "client_id=$GOOGLE_CLIENT_ID" \
            -d "client_secret=$GOOGLE_CLIENT_SECRET" \
            -d "refresh_token=$GOOGLE_REFRESH_TOKEN" \
            -d "grant_type=refresh_token" \
            | jq '.access_token | length > 0'
